### ISSUE TITLE
Learn how to integrate MathJax output in reST content to sphinx

### ISSUE THREAD

**Issue by rluce** [rluce/nupstup#6]

**Comment by simonbowly** [comment]
Supported natively through the math directive: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#math

Works out of the box but there may be some further configuration to look at here: https://www.sphinx-doc.org/en/master/usage/extensions/math.html#math-support

**Comment by simonbowly** [comment]
Use the [math directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-math) for formulation blocks and the [math role](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-math) for inline expressions. Examples from workforce.rst for reference:

https://github.com/rluce/nupstup/blob/6fcd7c4607cc50b5bb005420be9c1ae661d096f8/docs/source/library/workforce.rst?plain=1#L27-L53
